const db=window.supabase.createClient('https://wmsrwvlhivuycqmzjeea.supabase.co','sb_publishable_JCXBiV2IJJbQUsqLMVZcLg_oRpUrUuG');
const STATUS=['A fazer','Em preparo','Finalizado'],$=s=>document.querySelector(s),money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
let PRODUCTS=[],PAYMENT_METHODS=[],orders=[],users=[],profile=null,selected={},selectedPrices={},activePeriod='month',activeMetric='billing',chartGranularity='day',editingId=null,currentMode='admin',customStart=null,customEnd=null,editingProductId=null,editingPaymentId=null,editingUserId=null,orderPeriod='today',orderCustomStart=null,orderCustomEnd=null,dateContext='dashboard',channel,reloadTimer,suppressCardClickUntil=0;
function toast(m){const e=$('#toast');e.textContent=m;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2500)}
function esc(v=''){const d=document.createElement('div');d.textContent=v??'';return d.innerHTML}
function product(id){return PRODUCTS.find(x=>x.id===id)}
function paymentName(o){return o.payment||PAYMENT_METHODS.find(x=>x.id===o.paymentId)?.name||'—'}
function itemsLabel(items=[]){return items.map(x=>`${x.qty}× ${x.name||product(x.id)?.name||'Produto removido'}`).join(' · ')}
function number(o){return String(o.number||0).padStart(4,'0')}
function message(error,fallback='Não foi possível concluir a operação.'){console.error(error);return error?.message?.includes('duplicate key')?'Já existe um cadastro com esse nome.':fallback}
function busy(form,value){const b=form.querySelector('[type="submit"]');if(b){b.disabled=value;b.setAttribute('aria-busy',value)}}
function mapOrder(row){return{id:row.id,number:Number(row.order_number),client:row.client_name,value:Number(row.confirmed_total),status:row.status,paymentId:row.payment_method_id,payment:row.payment_method_name,createdAt:row.ordered_at,items:(row.order_items||[]).map(x=>({id:x.product_id,name:x.product_name,category:x.product_category,unitPrice:Number(x.unit_price),qty:Number(x.quantity)}))}}
async function loadProfile(user){const {data,error}=await db.from('profiles').select('*').eq('id',user.id).single();if(error)throw error;profile={id:data.id,name:data.name,email:data.email,role:data.role}}
async function loadData(){
 const [a,b,c,d]=await Promise.all([db.from('products').select('*').eq('active',true).order('name'),db.from('payment_methods').select('*').eq('active',true).order('name'),db.from('orders').select('*,order_items(*)').order('ordered_at',{ascending:false}),profile?.role==='admin'?db.from('profiles').select('*').order('name'):Promise.resolve({data:[profile],error:null})]);
 const error=a.error||b.error||c.error||d.error;if(error)throw error;
 PRODUCTS=(a.data||[]).map(x=>({id:x.id,name:x.name,category:x.category,price:Number(x.price),icon:'◦'}));PAYMENT_METHODS=(b.data||[]).map(x=>({id:x.id,name:x.name}));orders=(c.data||[]).map(mapOrder);users=(d.data||[]).map(x=>({id:x.id,name:x.name,email:x.email,role:x.role}));const current=users.find(x=>x.id===profile?.id);if(current)profile={...profile,...current};refreshCatalog();renderAll();
}
function subscribe(){if(channel)db.removeChannel(channel);const reload=()=>{clearTimeout(reloadTimer);reloadTimer=setTimeout(()=>loadData().catch(e=>toast(message(e,'Falha ao sincronizar os dados.'))),300)};channel=db.channel('rito-live').on('postgres_changes',{event:'*',schema:'public',table:'orders'},reload).on('postgres_changes',{event:'*',schema:'public',table:'order_items'},reload).on('postgres_changes',{event:'*',schema:'public',table:'products'},reload).on('postgres_changes',{event:'*',schema:'public',table:'payment_methods'},reload).subscribe()}
async function enter(user){try{await loadProfile(user);await loadData();subscribe();profile.role==='admin'?showMode():showApp('operation')}catch(e){toast(message(e,'Não foi possível carregar sua conta.'));await db.auth.signOut();showLogin()}}
function showLogin(){$('#loginScreen').hidden=false;$('#modeScreen').hidden=true;$('#appShell').hidden=true}
function periodFilter(type,start,end){const now=new Date();return o=>{const date=new Date(o.createdAt),diff=(now-date)/86400000;if(type==='today')return date.toDateString()===now.toDateString();if(type==='7d')return diff>=0&&diff<7;if(type==='month')return date.getMonth()===now.getMonth()&&date.getFullYear()===now.getFullYear();if(type==='custom')return date>=start&&date<=end;return true}}
function filteredOrders(){return orders.filter(periodFilter(activePeriod,customStart,customEnd))}
function orderFilteredOrders(){return orders.filter(periodFilter(orderPeriod,orderCustomStart,orderCustomEnd))}
function syncOrderPeriodUI(){const labels={today:'Pedidos de hoje','7d':'Pedidos dos últimos 7 dias',month:'Pedidos deste mês',all:'Histórico completo',custom:'Período personalizado'};$('#ordersPeriodTitle').textContent=labels[orderPeriod];document.querySelectorAll('[data-order-period]').forEach(b=>b.classList.toggle('active',b.dataset.orderPeriod===orderPeriod));renderKanban();renderOrdersCenter()}
const METRICS={billing:{label:'Faturamento',factor:1,format:'money'},netRevenue:{label:'Receita líquida',factor:.6,format:'money'},orders:{label:'Pedidos finalizados',format:'number'},ticket:{label:'Ticket médio',format:'money'},cost:{label:'Custo estimado',factor:.35,format:'money'}};
function metricValue(data,type){const total=data.reduce((s,o)=>s+Number(o.value),0);if(type==='orders')return data.length;if(type==='ticket')return data.length?total/data.length:0;return total*METRICS[type].factor}
function formatMetric(v,type){return METRICS[type].format==='number'?String(v):money(v)}
function renderDashboard(){const data=filteredOrders().filter(o=>o.status==='Finalizado');$('#revenueMetric').textContent=money(metricValue(data,'billing'));$('#netRevenueMetric').textContent=money(metricValue(data,'netRevenue'));$('#ordersMetric').textContent=data.length;$('#ticketMetric').textContent=money(metricValue(data,'ticket'));$('#costMetric').textContent=money(metricValue(data,'cost'));$('#revenueHelp').textContent=`${data.length} pedido${data.length===1?'':'s'} finalizado${data.length===1?'':'s'} no período`;renderChart(data);renderPayments(data);renderOperation();$('#recentOrders').innerHTML=orders.length?orders.slice(0,4).map(o=>`<button class="recent-row" data-edit-order="${o.id}"><span class="order-number">#${number(o)}</span><span><strong>${esc(o.client)}</strong><small>${esc(itemsLabel(o.items))}</small></span><span><strong>${money(o.value)}</strong><small class="status-chip ${statusClass(o.status)}">${o.status}</small></span></button>`).join(''):'<div class="empty-state"><span>▤</span><strong>Nenhum pedido ainda</strong><small>Os novos lançamentos aparecerão aqui.</small></div>';document.querySelectorAll('[data-edit-order]').forEach(b=>b.onclick=()=>{showView('pedidos');openOrder(b.dataset.editOrder)})}
function renderChart(data){const now=new Date(),points=[];if(chartGranularity==='month'){const count=activePeriod==='all'?12:activePeriod==='custom'?(customEnd.getFullYear()-customStart.getFullYear())*12+customEnd.getMonth()-customStart.getMonth()+1:1,base=activePeriod==='custom'?customEnd:now;for(let i=count-1;i>=0;i--){const date=new Date(base.getFullYear(),base.getMonth()-i,1),bucket=data.filter(o=>{const d=new Date(o.createdAt);return d.getMonth()===date.getMonth()&&d.getFullYear()===date.getFullYear()});points.push({label:date.toLocaleDateString('pt-BR',{month:'short',year:'2-digit'}).replace('.',''),value:metricValue(bucket,activeMetric)})}}else{const count=activePeriod==='today'?1:activePeriod==='7d'?7:activePeriod==='month'?now.getDate():activePeriod==='custom'?Math.floor((customEnd-customStart)/86400000)+1:30,base=activePeriod==='custom'?customEnd:now;for(let i=count-1;i>=0;i--){const date=new Date(base);date.setDate(date.getDate()-i);const bucket=data.filter(o=>new Date(o.createdAt).toDateString()===date.toDateString());points.push({label:date.toLocaleDateString('pt-BR',{day:'2-digit',month:'short'}).replace('.',''),value:metricValue(bucket,activeMetric)})}}const metric=METRICS[activeMetric],max=Math.max(...points.map(p=>p.value),1),unit=chartGranularity==='day'?'dia':'mês';$('#chartTitle').textContent=`${metric.label} por ${unit}`;$('#chartSubtitle').textContent='Somente pedidos finalizados no período selecionado';$('#chartTotal').textContent=formatMetric(metricValue(data,activeMetric),activeMetric);$('#barChart').innerHTML=points.map(p=>`<div class="bar-column" title="${p.label}: ${formatMetric(p.value,activeMetric)}"><span>${p.value?formatMetric(p.value,activeMetric).replace(',00',''):''}</span><div class="bar-track"><i style="height:${Math.max(p.value/max*100,p.value?8:2)}%"></i></div><small>${p.label}</small></div>`).join('')}
function renderPayments(data){const revenue=data.reduce((s,o)=>s+o.value,0);$('#paymentBreakdown').innerHTML=PAYMENT_METHODS.length?PAYMENT_METHODS.map((m,i)=>{const total=data.filter(o=>o.paymentId===m.id||o.payment===m.name).reduce((s,o)=>s+o.value,0),pct=revenue?Math.round(total/revenue*100):0;return `<div class="payment-row"><span><i class="payment-dot" style="background:hsl(${28+i*62} 35% 52%)"></i>${esc(m.name)}</span><div><b>${money(total)}</b><small>${pct}%</small></div><div class="payment-track"><i style="width:${pct}%"></i></div></div>`}).join(''):'<div class="empty-state compact"><strong>Nenhuma forma cadastrada</strong><small>Cadastre uma opção em Configurações.</small></div>'}
function renderOperation(){const today=orders.filter(o=>new Date(o.createdAt).toDateString()===new Date().toDateString()),counts=STATUS.map(s=>today.filter(o=>o.status===s).length);$('#operationStats').innerHTML=STATUS.map((s,i)=>`<button data-operation-status="${s}"><span class="operation-icon ${statusClass(s)}">${i===0?'◷':i===1?'♨':'✓'}</span><strong>${counts[i]}</strong><small>${s}</small></button>`).join('');document.querySelectorAll('[data-operation-status]').forEach(b=>b.onclick=()=>{orderPeriod='today';syncOrderPeriodUI();showView('pedidos');$('#statusFilter').value=b.dataset.operationStatus;renderOrdersCenter()});$('#orderBadge').textContent=counts[0]+counts[1]}
function statusClass(s){return s==='A fazer'?'todo':s==='Em preparo'?'doing':'done'}
function refreshCatalog(){const pay=$('#paymentSelect').value,payFilter=$('#paymentFilter').value,prodFilter=$('#productFilter').value;$('#paymentSelect').innerHTML='<option value="">Selecione uma forma</option>'+PAYMENT_METHODS.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('');$('#paymentFilter').innerHTML='<option value="">Todos</option>'+PAYMENT_METHODS.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('');$('#productFilter').innerHTML='<option value="">Todos</option>'+PRODUCTS.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('');if(PAYMENT_METHODS.some(x=>x.id===pay))$('#paymentSelect').value=pay;if(PAYMENT_METHODS.some(x=>x.id===payFilter))$('#paymentFilter').value=payFilter;if(PRODUCTS.some(x=>x.id===prodFilter))$('#productFilter').value=prodFilter}
function renderSettings(){$('#settingsProducts').innerHTML=PRODUCTS.length?PRODUCTS.map(x=>`<div class="setting-row"><span class="product-icon">◦</span><div><strong>${esc(x.name)}</strong><small>${esc(x.category)} · ${money(x.price)}</small></div><div class="setting-actions"><button data-edit-product="${x.id}">Editar</button><button class="danger-action" data-delete-product="${x.id}">Excluir</button></div></div>`).join(''):'<div class="empty-state"><strong>Nenhum produto cadastrado</strong><small>Crie o primeiro item do cardápio.</small></div>';$('#settingsPayments').innerHTML=PAYMENT_METHODS.length?PAYMENT_METHODS.map(x=>`<div class="setting-row"><span class="payment-setting-icon">$</span><div><strong>${esc(x.name)}</strong><small>Disponível nos pedidos</small></div><div class="setting-actions"><button data-edit-payment="${x.id}">Editar</button><button class="danger-action" data-delete-payment="${x.id}">Excluir</button></div></div>`).join(''):'<div class="empty-state"><strong>Nenhuma forma cadastrada</strong><small>Crie a primeira forma de pagamento.</small></div>';$('#settingsUsers').innerHTML=users.map(x=>`<div class="setting-row"><span class="user-setting-icon">${esc(x.name[0].toUpperCase())}</span><div><strong>${esc(x.name)}${x.id===profile.id?' · você':''}</strong><small>${esc(x.email)} · ${x.role==='admin'?'Administrador':'Operacional'}</small></div><div class="setting-actions"><button data-edit-user="${x.id}">Editar</button><button class="danger-action" data-delete-user="${x.id}">Excluir</button></div></div>`).join('');document.querySelectorAll('[data-edit-product]').forEach(b=>b.onclick=()=>openProduct(b.dataset.editProduct));document.querySelectorAll('[data-delete-product]').forEach(b=>b.onclick=()=>deleteProduct(b.dataset.deleteProduct));document.querySelectorAll('[data-edit-payment]').forEach(b=>b.onclick=()=>openPayment(b.dataset.editPayment));document.querySelectorAll('[data-delete-payment]').forEach(b=>b.onclick=()=>deletePayment(b.dataset.deletePayment));document.querySelectorAll('[data-edit-user]').forEach(b=>b.onclick=()=>openUser(b.dataset.editUser));document.querySelectorAll('[data-delete-user]').forEach(b=>b.onclick=()=>deleteUser(b.dataset.deleteUser))}
function openProduct(id=null){editingProductId=id;const x=PRODUCTS.find(p=>p.id===id);$('#productForm').reset();$('#productError').textContent='';$('#productDialogTitle').textContent=x?'Editar produto':'Novo produto';if(x){$('#productForm [name="name"]').value=x.name;$('#productForm [name="category"]').value=x.category;$('#productForm [name="price"]').value=x.price}$('#productDialog').showModal()}
function openPayment(id=null){editingPaymentId=id;const x=PAYMENT_METHODS.find(p=>p.id===id);$('#paymentForm').reset();$('#paymentError').textContent='';$('#paymentDialogTitle').textContent=x?'Editar forma':'Nova forma';if(x)$('#paymentForm [name="name"]').value=x.name;$('#paymentDialog').showModal()}
function openUser(id=null){editingUserId=id;const x=users.find(u=>u.id===id);$('#userForm').reset();$('#userError').textContent='';$('#userDialogTitle').textContent=x?'Editar usuário':'Novo usuário';const password=$('#userForm [name="password"]');password.required=!x;password.placeholder=x?'Deixe em branco para manter a senha':'Mínimo de 6 caracteres';if(x){$('#userForm [name="name"]').value=x.name;$('#userForm [name="email"]').value=x.email;$('#userForm [name="role"]').value=x.role}$('#userDialog').showModal()}
async function manageUser(payload){const {data,error}=await db.functions.invoke('manage-users',{body:payload});if(error){let detail;try{detail=await error.context?.json()}catch{}throw new Error(detail?.error||error.message)}if(data?.error)throw new Error(data.error);return data}
async function deleteUser(id){const x=users.find(u=>u.id===id);if(!x||!confirm(`Excluir o acesso de ${x.name}?`))return;try{await manageUser({action:'delete',id});await loadData();toast('Usuário excluído.')}catch(error){toast(message(error))}}
async function deleteProduct(id){const x=product(id);if(!x||!confirm(`Excluir ${x.name} do cardápio? Os pedidos anteriores serão preservados.`))return;const {error}=await db.from('products').update({active:false}).eq('id',id);if(error)return toast(message(error));await loadData();toast('Produto excluído. O histórico foi preservado.')}
async function deletePayment(id){const x=PAYMENT_METHODS.find(p=>p.id===id);if(!x||!confirm(`Excluir a forma ${x.name}? Os pedidos anteriores serão preservados.`))return;const {error}=await db.from('payment_methods').update({active:false}).eq('id',id);if(error)return toast(message(error));await loadData();toast('Forma excluída. O histórico foi preservado.')}
function renderOrdersCenter(){const term=$('#orderSearch').value.trim().toLowerCase(),status=$('#statusFilter').value,pay=$('#paymentFilter').value,prod=$('#productFilter').value,list=orderFilteredOrders().filter(o=>(!term||String(o.number).includes(term)||o.client.toLowerCase().includes(term)||itemsLabel(o.items).toLowerCase().includes(term))&&(!status||o.status===status)&&(!pay||o.paymentId===pay)&&(!prod||o.items.some(x=>x.id===prod)));$('#filteredCount').textContent=`${list.length} pedido${list.length===1?'':'s'}`;$('#allOrdersTable').innerHTML=list.length?list.map(o=>`<tr data-row="${o.id}"><td><strong>#${number(o)}</strong></td><td>${new Date(o.createdAt).toLocaleString('pt-BR',{day:'2-digit',month:'2-digit',year:'2-digit',hour:'2-digit',minute:'2-digit'})}</td><td>${esc(o.client)}</td><td>${esc(itemsLabel(o.items))}</td><td>${esc(paymentName(o))}</td><td><span class="status-chip ${statusClass(o.status)}">${o.status}</span></td><td><strong>${money(o.value)}</strong></td><td><button class="delete-order" data-delete="${o.id}">×</button></td></tr>`).join(''):'<tr><td colspan="8"><div class="empty-state compact"><strong>Nenhum pedido encontrado</strong><small>Crie um pedido ou ajuste os filtros.</small></div></td></tr>';document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=e=>{e.stopPropagation();deleteOrder(b.dataset.delete)});document.querySelectorAll('[data-row]').forEach(r=>r.onclick=()=>openOrder(r.dataset.row))}
async function deleteOrder(id,confirmed=false){const o=orders.find(x=>x.id===id);if(!o||(!confirmed&&!confirm(`Apagar definitivamente o pedido #${number(o)}?`)))return false;const {error}=await db.from('orders').delete().eq('id',id);if(error){toast(message(error));return false}orders=orders.filter(x=>x.id!==id);renderAll();toast('Pedido apagado.');return true}
async function deleteEditing(){if(editingId&&confirm(`Apagar definitivamente o pedido #${number(orders.find(x=>x.id===editingId))}?`)&&await deleteOrder(editingId,true)){$('#orderDialog').close();showView('pedidos')}}
function renderKanban(){const all=orderFilteredOrders(),counts=STATUS.map(s=>all.filter(o=>o.status===s).length);$('#todoCount').textContent=counts[0];$('#doingCount').textContent=counts[1];$('#kanban').innerHTML=STATUS.map((s,i)=>{const list=all.filter(o=>o.status===s);return `<section class="kanban-column" data-kanban-status="${s}"><header><div><i class="dot ${statusClass(s)}"></i><strong>${s}</strong><span>${list.length}</span></div>${i===0?'<button class="mini-add" data-new-order>＋</button>':''}</header><div class="kanban-list">${list.length?list.map(o=>orderCard(o,i)).join(''):'<div class="empty-column">Nenhum pedido neste período</div>'}</div></section>`}).join('');document.querySelectorAll('[data-move]').forEach(b=>b.onclick=e=>{e.stopPropagation();moveOrder(b.dataset.move,+b.dataset.direction)});document.querySelectorAll('[data-card]').forEach(c=>c.onclick=()=>{if(Date.now()>suppressCardClickUntil)openOrder(c.dataset.card)});document.querySelectorAll('[data-new-order]').forEach(b=>b.onclick=()=>openOrder());enableKanbanDrag()}
function orderCard(o,i){return `<article class="order-card" data-card="${o.id}" tabindex="0"><div class="card-top"><span>#${number(o)}</span><small>${new Date(o.createdAt).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}</small></div><h3>${esc(o.client)}</h3><p>${esc(itemsLabel(o.items))}</p><div class="card-payment"><span>${esc(paymentName(o))}</span><strong>${money(o.value)}</strong></div><div class="card-actions">${i>0?`<button data-move="${o.id}" data-direction="-1">←</button>`:'<span></span>'}${i<2?`<button class="advance" data-move="${o.id}" data-direction="1">${i===0?'Iniciar preparo':'Finalizar'} →</button>`:'<span class="finished-label">✓ Concluído</span>'}</div></article>`}
async function setOrderStatus(id,next){const o=orders.find(x=>x.id===id);if(!o||!STATUS.includes(next)||o.status===next)return;const {error}=await db.from('orders').update({status:next}).eq('id',id);if(error)return toast(message(error));o.status=next;renderAll();toast(next==='Finalizado'?'Pedido finalizado.':'Pedido atualizado.')}
async function moveOrder(id,d){const o=orders.find(x=>x.id===id),next=STATUS[STATUS.indexOf(o.status)+d];if(next)await setOrderStatus(id,next)}
function enableKanbanDrag(){const kanban=$('#kanban');let timer=null,state=null,startX=0,startY=0;const clearTarget=()=>document.querySelectorAll('.kanban-column.drop-target').forEach(x=>x.classList.remove('drop-target'));const cleanup=()=>{if(!state)return;state.card.classList.remove('drag-source');state.ghost.remove();document.body.classList.remove('kanban-dragging');clearTarget();state=null;suppressCardClickUntil=Date.now()+600};const finish=async e=>{clearTimeout(timer);timer=null;if(!state)return;const target=document.elementFromPoint(e.clientX,e.clientY)?.closest('.kanban-column'),next=target?.dataset.kanbanStatus,id=state.id;cleanup();if(next)await setOrderStatus(id,next)};document.querySelectorAll('[data-card]').forEach(card=>{card.addEventListener('pointerdown',e=>{if(e.button!==0||e.target.closest('button'))return;startX=e.clientX;startY=e.clientY;timer=setTimeout(()=>{const rect=card.getBoundingClientRect(),ghost=card.cloneNode(true);ghost.className='order-card drag-ghost';ghost.style.width=`${rect.width}px`;document.body.appendChild(ghost);card.classList.add('drag-source');document.body.classList.add('kanban-dragging');card.setPointerCapture(e.pointerId);state={id:card.dataset.card,card,ghost};ghost.style.transform=`translate3d(${e.clientX-rect.width/2}px,${e.clientY-35}px,0)`;navigator.vibrate?.(25)},380)});card.addEventListener('pointermove',e=>{if(!state){if(Math.hypot(e.clientX-startX,e.clientY-startY)>9){clearTimeout(timer);timer=null}return}e.preventDefault();state.ghost.style.transform=`translate3d(${e.clientX-state.ghost.offsetWidth/2}px,${e.clientY-35}px,0)`;if(e.clientX<45)kanban.scrollLeft-=12;else if(e.clientX>innerWidth-45)kanban.scrollLeft+=12;clearTarget();document.elementFromPoint(e.clientX,e.clientY)?.closest('.kanban-column')?.classList.add('drop-target')},{passive:false});card.addEventListener('pointerup',finish);card.addEventListener('pointercancel',()=>{clearTimeout(timer);timer=null;cleanup()})})}
function renderProducts(){$('#productGrid').innerHTML=PRODUCTS.length?PRODUCTS.map(p=>`<article class="product-card ${selected[p.id]?'selected':''}"><span class="product-icon">◦</span><div><strong>${esc(p.name)}</strong><small>${esc(p.category)} · ${money(p.price)}</small></div><div class="stepper"><button type="button" data-product="${p.id}" data-change="-1">−</button><b>${selected[p.id]||0}</b><button type="button" data-product="${p.id}" data-change="1">＋</button></div></article>`).join(''):'<div class="empty-state product-empty"><strong>Nenhum produto disponível</strong><small>Cadastre itens em Configurações.</small></div>';document.querySelectorAll('[data-product]').forEach(b=>b.onclick=()=>{const id=b.dataset.product;if(!(id in selectedPrices))selectedPrices[id]=product(id).price;selected[id]=Math.max(0,(selected[id]||0)+Number(b.dataset.change));if(!selected[id]){delete selected[id];delete selectedPrices[id]}renderProducts();updateTotal()})}
function updateTotal(){const total=Object.entries(selected).reduce((s,[id,q])=>s+(selectedPrices[id]??product(id)?.price??0)*q,0);$('#calculatedTotal').textContent=money(total);$('#confirmedTotal').value=total?total.toFixed(2):''}
function localDate(v){const d=new Date(v),offset=d.getTimezoneOffset();return new Date(d.getTime()-offset*60000).toISOString().slice(0,10)}
function clock(v){const d=new Date(v);return `${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`}
function openOrder(id=null){editingId=id;const o=id?orders.find(x=>x.id===id):null,available=o?o.items.filter(x=>product(x.id)):[];selected=Object.fromEntries(available.map(x=>[x.id,x.qty]));selectedPrices=Object.fromEntries(available.map(x=>[x.id,x.unitPrice]));$('#orderForm').reset();refreshCatalog();$('#orderError').textContent='';$('#orderDialogEyebrow').textContent=o?'EDITAR PEDIDO':'NOVO PEDIDO';$('#orderDialogTitle').textContent=o?`Pedido #${number(o)}`:'Monte o pedido';$('#orderSubmit').innerHTML=o?'Salvar alterações':'Criar pedido <span>→</span>';$('#deleteOrderBtn').hidden=!o;const moment=o?.createdAt||new Date();$('#orderForm [name="orderDate"]').value=localDate(moment);$('#orderForm [name="orderTime"]').value=clock(moment);if(o){$('#orderForm [name="client"]').value=o.client==='Balcão'?'':o.client;$('#orderForm [name="payment"]').value=o.paymentId||'';$('#orderForm [name="status"]').value=o.status}renderProducts();updateTotal();if(o)$('#confirmedTotal').value=o.value.toFixed(2);$('#orderDialog').showModal()}
function closeOrder(){$('#orderDialog').close();if(!$('#appShell').hidden)showView('pedidos')}
function showView(id){if(currentMode==='operation')id='pedidos';document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id));document.querySelectorAll('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.view===id));const t={dashboard:'Visão geral',pedidos:'Pedidos',configuracoes:'Configurações'},s={dashboard:'Acompanhe o pulso da operação em tempo real.',pedidos:'Organize a fila e mantenha o time em sintonia.',configuracoes:'Personalize o cardápio e os meios de pagamento.'};$('#pageTitle').textContent=t[id];$('.subtitle').textContent=s[id];$('#sidebar').classList.remove('open');if(id==='pedidos'){renderKanban();renderOrdersCenter()}if(id==='configuracoes')renderSettings();window.scrollTo({top:0,behavior:'smooth'})}
function renderAll(){renderDashboard();renderKanban();renderOrdersCenter();renderSettings()}
function initial(){return profile?.name?.trim()[0]?.toLocaleUpperCase('pt-BR')||'A'}
function applyProfile(){$('#userName').textContent=profile.name;$('#userAvatar').textContent=initial();$('#profileAvatar').textContent=initial();$('#userRole').textContent=profile.role==='admin'?'Administrador':'Operacional'}
function openProfile(){applyProfile();$('#profileName').value=profile.name;$('#profileEmail').value=profile.email;$('#profilePassword').value='';$('#profileError').textContent='';$('#profileDialog').showModal()}
function closeProfile(){$('#profileDialog').close()}
function showMode(){$('#loginScreen').hidden=true;$('#appShell').hidden=true;$('#modeScreen').hidden=false}
function showApp(mode){if(profile.role!=='admin')mode='operation';currentMode=mode;sessionStorage.setItem('rito-mode',mode);$('#loginScreen').hidden=true;$('#modeScreen').hidden=true;$('#appShell').hidden=false;document.body.classList.toggle('operational-mode',mode==='operation');document.querySelectorAll('.admin-only').forEach(e=>e.hidden=mode==='operation');$('#modeSwitch').hidden=profile.role!=='admin';$('#modeSwitchLabel').textContent=mode==='admin'?'Administrativo':'Operacional';applyProfile();renderAll();showView(mode==='admin'?'dashboard':'pedidos')}
$('#loginForm').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget,data=new FormData(form);busy(form,true);$('#loginError').textContent='';const {data:result,error}=await db.auth.signInWithPassword({email:data.get('email').trim(),password:data.get('password')});busy(form,false);if(error)return $('#loginError').textContent='E-mail ou senha incorretos.';await enter(result.user)};
$('#togglePassword').onclick=()=>{const i=$('#loginForm input[name="password"]');i.type=i.type==='password'?'text':'password'};
document.querySelectorAll('[data-select-mode]').forEach(b=>b.onclick=()=>showApp(b.dataset.selectMode));$('#modeSwitch').onclick=()=>showApp(currentMode==='admin'?'operation':'admin');$('#profileBtn').onclick=openProfile;$('#closeProfile').onclick=closeProfile;$('#cancelProfile').onclick=closeProfile;$('#profileName').oninput=e=>{$('#profileAvatar').textContent=e.target.value.trim()[0]?.toUpperCase()||'A'};
$('#profileForm').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget,d=new FormData(form),name=d.get('name').trim(),password=d.get('password');if(!name)return $('#profileError').textContent='Informe um nome.';if(password&&password.length<6)return $('#profileError').textContent='A senha deve ter pelo menos 6 caracteres.';busy(form,true);let {error}=await db.rpc('update_own_profile',{p_name:name});if(!error&&password)({error}=await db.auth.updateUser({password}));busy(form,false);if(error)return $('#profileError').textContent=message(error,'Não foi possível atualizar. Execute a migration complementar.');profile.name=name;const u=users.find(x=>x.id===profile.id);if(u)u.name=name;applyProfile();renderSettings();closeProfile();toast('Perfil atualizado com sucesso.')};
$('#newProductBtn').onclick=()=>openProduct();$('#newPaymentBtn').onclick=()=>openPayment();$('#newUserBtn').onclick=()=>openUser();document.querySelectorAll('[data-close-product]').forEach(b=>b.onclick=()=>$('#productDialog').close());document.querySelectorAll('[data-close-payment]').forEach(b=>b.onclick=()=>$('#paymentDialog').close());document.querySelectorAll('[data-close-user]').forEach(b=>b.onclick=()=>$('#userDialog').close());
$('#productForm').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget,d=new FormData(form),payload={name:d.get('name').trim(),category:d.get('category').trim(),price:Number(d.get('price')),active:true};if(PRODUCTS.some(x=>x.id!==editingProductId&&x.name.toLowerCase()===payload.name.toLowerCase()))return $('#productError').textContent='Já existe um produto com esse nome.';busy(form,true);const r=editingProductId?await db.from('products').update(payload).eq('id',editingProductId):await db.from('products').insert(payload);busy(form,false);if(r.error)return $('#productError').textContent=message(r.error);await loadData();$('#productDialog').close();toast(editingProductId?'Produto atualizado. O preço anterior foi preservado nos pedidos existentes.':'Produto criado.')};
$('#paymentForm').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget,d=new FormData(form),payload={name:d.get('name').trim(),active:true};if(PAYMENT_METHODS.some(x=>x.id!==editingPaymentId&&x.name.toLowerCase()===payload.name.toLowerCase()))return $('#paymentError').textContent='Já existe uma forma com esse nome.';busy(form,true);const r=editingPaymentId?await db.from('payment_methods').update(payload).eq('id',editingPaymentId):await db.from('payment_methods').insert(payload);busy(form,false);if(r.error)return $('#paymentError').textContent=message(r.error);await loadData();$('#paymentDialog').close();toast(editingPaymentId?'Forma atualizada.':'Forma criada.')};
$('#userForm').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget,d=new FormData(form),payload={action:editingUserId?'update':'create',id:editingUserId||undefined,name:d.get('name').trim(),email:d.get('email').trim().toLowerCase(),password:d.get('password'),role:d.get('role')};if(users.some(x=>x.id!==editingUserId&&x.email.toLowerCase()===payload.email))return $('#userError').textContent='Este e-mail já está em uso.';if(!editingUserId&&payload.password.length<6)return $('#userError').textContent='A senha deve ter pelo menos 6 caracteres.';busy(form,true);try{await manageUser(payload);await loadData();$('#userDialog').close();toast(editingUserId?'Usuário atualizado.':'Usuário criado.')}catch(error){$('#userError').textContent=message(error)}finally{busy(form,false)}};
async function logout(){if(channel)await db.removeChannel(channel);await db.auth.signOut();profile=null;orders=[];PRODUCTS=[];PAYMENT_METHODS=[];users=[];sessionStorage.removeItem('rito-mode');showLogin()}$('#logoutBtn').onclick=logout;$('#modeLogout').onclick=logout;document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>showView(b.dataset.go));$('#menuBtn').onclick=()=>$('#sidebar').classList.toggle('open');document.addEventListener('pointerdown',e=>{const sidebar=$('#sidebar');if(innerWidth<=760&&sidebar.classList.contains('open')&&!sidebar.contains(e.target)&&!$('#menuBtn').contains(e.target))sidebar.classList.remove('open')});$('#newOrderBtn').onclick=()=>openOrder();$('#closeDialog').onclick=closeOrder;$('#cancelOrder').onclick=closeOrder;$('#deleteOrderBtn').onclick=deleteEditing;
$('#orderDialog').onclick=e=>{if(e.target===$('#orderDialog'))closeOrder()};[['productDialog',()=>$('#productDialog').close()],['paymentDialog',()=>$('#paymentDialog').close()],['userDialog',()=>$('#userDialog').close()],['profileDialog',closeProfile]].forEach(([id,close])=>$('#'+id).addEventListener('click',e=>{if(e.target===$('#'+id))close()}));
$('#periodTabs').onclick=e=>{if(!e.target.dataset.period)return;if(e.target.dataset.period==='custom'){dateContext='dashboard';$('#dateError').textContent='';return $('#dateDialog').showModal()}activePeriod=e.target.dataset.period;document.querySelectorAll('#periodTabs button').forEach(b=>b.classList.toggle('active',b===e.target));renderDashboard()};$('#ordersPeriodTabs').onclick=e=>{if(!e.target.dataset.orderPeriod)return;if(e.target.dataset.orderPeriod==='custom'){dateContext='orders';$('#dateError').textContent='';return $('#dateDialog').showModal()}orderPeriod=e.target.dataset.orderPeriod;syncOrderPeriodUI()};document.querySelectorAll('[data-metric]').forEach(c=>c.onclick=()=>{activeMetric=c.dataset.metric;document.querySelectorAll('[data-metric]').forEach(x=>x.classList.toggle('active',x===c));renderDashboard()});$('#chartGranularity').onclick=e=>{if(!e.target.dataset.granularity)return;chartGranularity=e.target.dataset.granularity;document.querySelectorAll('#chartGranularity button').forEach(b=>b.classList.toggle('active',b===e.target));renderDashboard()};
$('#orderForm').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget,items=Object.entries(selected).map(([id,qty])=>{const p=product(id);return{product_id:id,product_name:p?.name||id,product_category:p?.category||'',unit_price:selectedPrices[id]??p?.price??0,quantity:qty}});if(!items.length)return $('#orderError').textContent='Selecione pelo menos um produto.';const d=new FormData(form),payment=PAYMENT_METHODS.find(x=>x.id===d.get('payment'));if(!payment)return $('#orderError').textContent='Selecione uma forma de pagamento.';busy(form,true);const {error}=await db.rpc('save_order',{p_order_id:editingId,p_client_name:d.get('client').trim()||'Balcão',p_confirmed_total:Number(d.get('value')),p_status:d.get('status'),p_payment_method_id:payment.id,p_payment_method_name:payment.name,p_ordered_at:new Date(`${d.get('orderDate')}T${d.get('orderTime')}:00`).toISOString(),p_items:items});busy(form,false);if(error)return $('#orderError').textContent=message(error,'Não foi possível salvar. Execute a migration complementar.');const edited=!!editingId;await loadData();closeOrder();showView('pedidos');toast(edited?'Pedido atualizado com sucesso.':'Pedido criado e enviado para a fila.')};
['orderSearch','statusFilter','paymentFilter','productFilter'].forEach(id=>$('#'+id).oninput=renderOrdersCenter);$('#clearFilters').onclick=()=>{$('#orderSearch').value='';$('#statusFilter').value='';$('#paymentFilter').value='';$('#productFilter').value='';renderOrdersCenter()};$('#closeDate').onclick=()=>$('#dateDialog').close();$('#cancelDate').onclick=()=>$('#dateDialog').close();$('#dateForm').onsubmit=e=>{e.preventDefault();const d=new FormData(e.currentTarget),start=d.get('start'),end=d.get('end')||start;if(!start)return;const a=new Date(start+'T00:00:00'),b=new Date(end+'T23:59:59.999');if(b<a)return $('#dateError').textContent='A data final deve ser igual ou posterior à inicial.';if(dateContext==='orders'){orderCustomStart=a;orderCustomEnd=b;orderPeriod='custom';syncOrderPeriodUI()}else{customStart=a;customEnd=b;activePeriod='custom';document.querySelectorAll('#periodTabs button').forEach(x=>x.classList.toggle('active',x.dataset.period==='custom'));renderDashboard()}$('#dateDialog').close()};
$('#dateLabel').textContent=new Date().toLocaleDateString('pt-BR',{weekday:'long',day:'2-digit',month:'long'});async function bootstrap(){const {data,error}=await db.auth.getSession();if(error||!data.session)return showLogin();await enter(data.session.user)}db.auth.onAuthStateChange(e=>{if(e==='SIGNED_OUT')showLogin()});bootstrap();
