const db=window.supabase.createClient('https://wmsrwvlhivuycqmzjeea.supabase.co','sb_publishable_JCXBiV2IJJbQUsqLMVZcLg_oRpUrUuG');
const $=selector=>document.querySelector(selector),money=value=>Number(value||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
let orders=[],products=[],payments=[],activeTab='active',activePeriod='today',customStart=null,customEnd=null,expandedId=null,editingId=null,pendingFinalizeId=null,selected={},selectedPrices={},channel=null;
function esc(value=''){const element=document.createElement('div');element.textContent=value??'';return element.innerHTML}
function number(order){return String(order.order_number||0).padStart(4,'0')}
function statusClass(status){return status==='A fazer'?'todo':status==='Em preparo'?'doing':'done'}
function itemsLabel(items=[]){return items.map(item=>`${item.quantity}× ${item.product_name}`).join(' · ')||'Pedido sem itens'}
function toast(message){const element=$('#toast');element.textContent=message;element.classList.add('show');setTimeout(()=>element.classList.remove('show'),2400)}
function mapOrder(row){return{...row,confirmed_total:Number(row.confirmed_total),order_items:row.order_items||[]}}
function localDate(value){const date=new Date(value),offset=date.getTimezoneOffset();return new Date(date.getTime()-offset*60000).toISOString().slice(0,10)}
function clock(value){const date=new Date(value);return `${String(date.getHours()).padStart(2,'0')}:${String(date.getMinutes()).padStart(2,'0')}`}
function periodFilter(order){const date=new Date(order.ordered_at),now=new Date(),diff=(now-date)/86400000;if(activePeriod==='today')return date.toDateString()===now.toDateString();if(activePeriod==='7d')return diff>=0&&diff<7;if(activePeriod==='month')return date.getMonth()===now.getMonth()&&date.getFullYear()===now.getFullYear();if(activePeriod==='custom')return date>=customStart&&date<=customEnd;return true}
function actionButtons(order){if(order.status==='A fazer')return `<button data-status="Em preparo">Em preparo</button><button data-status="Finalizado">Finalizado</button>`;if(order.status==='Em preparo')return `<button data-status="A fazer">Retomar: A fazer</button><button data-status="Finalizado">Finalizado</button>`;return `<button data-status="Em preparo">Retomar preparo</button><button data-status="A fazer">Retomar: A fazer</button>`}
function orderCard(order){const expanded=expandedId===order.id,date=new Date(order.ordered_at),summary=itemsLabel(order.order_items),client=order.client_name&&order.client_name!=='Balcão'?order.client_name:'';return `<article class="order-card ${statusClass(order.status)} ${expanded?'expanded':''}" data-order="${order.id}" tabindex="0" aria-expanded="${expanded}"><div class="card-head"><div class="card-number">${client?`<small>${esc(client)}</small>`:''}<strong>#${number(order)}</strong><p class="peek-items">${esc(summary)}</p></div><span class="status">${esc(order.status)}</span></div><div class="card-body"><div class="card-content"><h2 class="client">${esc(order.client_name||'Balcão')}</h2><p class="items">${esc(summary)}</p><div class="meta"><div><small>HORÁRIO</small><strong>${date.toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}</strong></div><div><small>PAGAMENTO</small><strong>${esc(order.payment_method_name||'—')}</strong></div><div><small>TOTAL</small><strong>${money(order.confirmed_total)}</strong></div><button class="edit-link" data-edit>Editar pedido</button></div></div><div class="card-actions">${actionButtons(order)}</div></div></article>`}
function render(){const filtered=orders.filter(periodFilter),active=filtered.filter(order=>order.status!=='Finalizado'),done=filtered.filter(order=>order.status==='Finalizado').sort((a,b)=>new Date(b.updated_at)-new Date(a.updated_at)),list=activeTab==='active'?active:done;$('#activeCount').textContent=active.length;$('#doneCount').textContent=done.length;$('#queueSummary').textContent=active.length?`${active.length} pedido${active.length===1?'':'s'} em andamento no período`:'Operação em dia — nenhuma pendência';$('#wallet').innerHTML=list.length?list.map(orderCard).join(''):`<div class="empty"><span>✓</span><strong>${activeTab==='active'?'Fila organizada':'Nenhum pedido finalizado'}</strong><small>${activeTab==='active'?'Os próximos pedidos aparecerão aqui.':'Os pedidos concluídos serão guardados nesta aba.'}</small></div>`;document.querySelectorAll('[data-order]').forEach(card=>{card.onclick=event=>{const id=card.dataset.order;if(event.target.closest('button'))return;expandedId=expandedId===id?null:id;render()};card.onkeydown=event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();expandedId=expandedId===card.dataset.order?null:card.dataset.order;render()}};card.querySelectorAll('[data-status]').forEach(button=>button.onclick=event=>{event.stopPropagation();requestStatus(card.dataset.order,button.dataset.status)});card.querySelector('[data-edit]').onclick=event=>{event.stopPropagation();openOrder(card.dataset.order)}})}
function requestStatus(id,status){if(status!=='Finalizado')return updateStatus(id,status);const order=orders.find(item=>item.id===id);if(!order)return;pendingFinalizeId=id;$('#finalizeText').textContent=`O pedido #${number(order)} será movido para a aba de finalizados.`;$('#finalizeDialog').showModal()}
async function updateStatus(id,status){const order=orders.find(item=>item.id===id);if(!order||order.status===status)return;const previous=order.status;order.status=status;expandedId=null;render();const {error}=await db.from('orders').update({status}).eq('id',id);if(error){order.status=previous;render();return toast('Não foi possível atualizar o pedido.')}toast(status==='Finalizado'?'Pedido finalizado.':'Status atualizado.')}
function renderProducts(){if(!products.length){$('#productGrid').innerHTML='<div class="empty"><strong>Nenhum produto cadastrado</strong></div>';return}$('#productGrid').innerHTML=products.map(product=>`<article class="product-option ${selected[product.id]?'selected':''}"><strong>${esc(product.name)}</strong><small>${esc(product.category)} · ${money(product.price)}</small><div class="stepper"><button type="button" data-product="${product.id}" data-change="-1">−</button><b>${selected[product.id]||0}</b><button type="button" data-product="${product.id}" data-change="1">＋</button></div></article>`).join('');document.querySelectorAll('[data-product]').forEach(button=>button.onclick=()=>{const id=button.dataset.product,product=products.find(item=>item.id===id);if(!(id in selectedPrices))selectedPrices[id]=product.price;selected[id]=Math.max(0,(selected[id]||0)+Number(button.dataset.change));if(!selected[id]){delete selected[id];delete selectedPrices[id]}renderProducts();updateCalculatedTotal()})}
function updateCalculatedTotal(){const total=Object.entries(selected).reduce((sum,[id,quantity])=>sum+(selectedPrices[id]??products.find(item=>item.id===id)?.price??0)*quantity,0);$('#calculatedTotal').textContent=money(total);$('#confirmedTotal').value=total?total.toFixed(2):''}
function refreshPaymentSelect(value=''){$('#paymentSelect').innerHTML='<option value="">Selecione uma forma</option>'+payments.map(payment=>`<option value="${payment.id}">${esc(payment.name)}</option>`).join('');$('#paymentSelect').value=value}
function openOrder(id=null){const order=id?orders.find(item=>item.id===id):null;editingId=id;selected={};selectedPrices={};if(order)order.order_items.forEach(item=>{if(products.some(product=>product.id===item.product_id)){selected[item.product_id]=Number(item.quantity);selectedPrices[item.product_id]=Number(item.unit_price)}});$('#orderForm').reset();$('#orderError').textContent='';$('#orderEyebrow').textContent=order?'EDITAR PEDIDO':'NOVO PEDIDO';$('#orderTitle').textContent=order?`Pedido #${number(order)}`:'Monte o pedido';$('#orderSubmit').textContent=order?'Salvar alterações':'Criar pedido';const moment=order?.ordered_at||new Date();$('#orderForm [name="orderDate"]').value=localDate(moment);$('#orderForm [name="orderTime"]').value=clock(moment);if(order)$('#orderForm [name="client"]').value=order.client_name==='Balcão'?'':order.client_name;refreshPaymentSelect(order?.payment_method_id||'');if(order)$('#orderForm [name="status"]').value=order.status;renderProducts();updateCalculatedTotal();if(order)$('#confirmedTotal').value=order.confirmed_total.toFixed(2);$('#orderDialog').showModal()}
function closeOrder(){$('#orderDialog').close();editingId=null}
async function load(){const [ordersResult,productsResult,paymentsResult]=await Promise.all([db.from('orders').select('*,order_items(*)').order('ordered_at',{ascending:false}),db.from('products').select('*').eq('active',true).order('name'),db.from('payment_methods').select('*').eq('active',true).order('name')]);const error=ordersResult.error||productsResult.error||paymentsResult.error;if(error)return toast('Não foi possível carregar a operação.');orders=(ordersResult.data||[]).map(mapOrder);products=(productsResult.data||[]).map(item=>({...item,price:Number(item.price)}));payments=paymentsResult.data||[];render()}
async function start(){const {data}=await db.auth.getSession();if(!data.session){$('.mobile-shell').hidden=true;$('#authGate').hidden=false;return}await load();channel=db.channel('rito-rev2').on('postgres_changes',{event:'*',schema:'public',table:'orders'},()=>load()).on('postgres_changes',{event:'*',schema:'public',table:'order_items'},()=>load()).subscribe()}
document.querySelectorAll('[data-tab]').forEach(button=>button.onclick=()=>{activeTab=button.dataset.tab;expandedId=null;document.querySelectorAll('[data-tab]').forEach(item=>item.classList.toggle('active',item===button));render()});
document.querySelectorAll('[data-period]').forEach(button=>button.onclick=()=>{if(button.dataset.period==='custom'){$('#dateError').textContent='';return $('#dateDialog').showModal()}activePeriod=button.dataset.period;expandedId=null;const labels={today:'Pedidos de hoje','7d':'Últimos 7 dias',month:'Pedidos deste mês',all:'Histórico completo'};$('#periodTitle').textContent=labels[activePeriod];document.querySelectorAll('[data-period]').forEach(item=>item.classList.toggle('active',item===button));render()});
$('#newOrderButton').onclick=()=>openOrder();$('#closeOrder').onclick=closeOrder;$('#cancelOrder').onclick=closeOrder;$('#orderDialog').onclick=event=>{if(event.target===$('#orderDialog'))closeOrder()};
$('#adminButton').onclick=()=>$('#adminDialog').showModal();$('#confirmAdmin').onclick=()=>{sessionStorage.setItem('rito-mode','admin');location.href='../?mode=admin'};
$('#confirmFinalize').onclick=()=>{const id=pendingFinalizeId;pendingFinalizeId=null;if(id)updateStatus(id,'Finalizado')};$('#finalizeDialog').addEventListener('close',()=>{if($('#finalizeDialog').returnValue!=='default')pendingFinalizeId=null});
$('#closeDate').onclick=()=>$('#dateDialog').close();$('#cancelDate').onclick=()=>$('#dateDialog').close();$('#dateDialog').onclick=event=>{if(event.target===$('#dateDialog'))$('#dateDialog').close()};$('#dateForm').onsubmit=event=>{event.preventDefault();const data=new FormData(event.currentTarget),start=data.get('start'),end=data.get('end')||start;if(!start)return;const first=new Date(start+'T00:00:00'),last=new Date(end+'T23:59:59.999');if(last<first)return $('#dateError').textContent='A data final deve ser igual ou posterior à inicial.';customStart=first;customEnd=last;activePeriod='custom';expandedId=null;$('#periodTitle').textContent=start===end||!data.get('end')?`Pedidos de ${first.toLocaleDateString('pt-BR')}`:`${first.toLocaleDateString('pt-BR')} a ${last.toLocaleDateString('pt-BR')}`;document.querySelectorAll('[data-period]').forEach(item=>item.classList.toggle('active',item.dataset.period==='custom'));$('#dateDialog').close();render()};
$('#orderForm').onsubmit=async event=>{event.preventDefault();const form=event.currentTarget,data=new FormData(form),items=Object.entries(selected).map(([id,quantity])=>{const product=products.find(item=>item.id===id);return{product_id:id,product_name:product.name,product_category:product.category,unit_price:selectedPrices[id]??product.price,quantity}}),payment=payments.find(item=>item.id===data.get('payment'));if(!items.length)return $('#orderError').textContent='Selecione pelo menos um produto.';if(!payment)return $('#orderError').textContent='Selecione uma forma de pagamento.';const submit=$('#orderSubmit');submit.disabled=true;const {error}=await db.rpc('save_order',{p_order_id:editingId,p_client_name:data.get('client').trim()||'Balcão',p_confirmed_total:Number(data.get('value')),p_status:data.get('status'),p_payment_method_id:payment.id,p_payment_method_name:payment.name,p_ordered_at:new Date(`${data.get('orderDate')}T${data.get('orderTime')}:00`).toISOString(),p_items:items});submit.disabled=false;if(error)return $('#orderError').textContent='Não foi possível salvar o pedido.';const edited=!!editingId;closeOrder();await load();toast(edited?'Pedido atualizado.':'Pedido criado e enviado para a fila.')};
$('#todayLabel').textContent=new Date().toLocaleDateString('pt-BR',{weekday:'long',day:'2-digit',month:'long'});start();
